DjangoTest/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path


urlpatterns = [
     
    path('', include('authenticate.urls')),
    path('', include('ticket.urls')),
    path('admin/', admin.site.urls),
]

ticket/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from ticket.views import *

app_name = 'ticket'

urlpatterns = [
    path('', login_required(TicketList.as_view()), name='list'),
    path('get-tickets/', GetTicketList.as_view(), name='get_ticket'),
    path('new/', login_required(TicketNew.as_view()), name='ticket_new'),
]

ticket/models.py
from django.db import models

# Create your models here.

import datetime

from dateutil.relativedelta import relativedelta
from django.db import models
from django.contrib import admin

class Ticket(models.Model):
    tipo_estado = (
        (1, 'Abierto'),
        (2, 'Pendiente'),
        (3, 'En Proceso'),
        (4, 'Resuelto'),
        (3, 'Cerrado'),
    )
    titulo         = models.CharField(max_length=50)
    descripcion    = models.CharField(max_length=300)
    estado         = models.IntegerField(choices=tipo_estado)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    @property
    def tiempo_creacion(self):
        return relativedelta(datetime.datetime.now().date(), self.fecha_creacion.date()).days

    def __str__(self):
        return '%s' % (self.descripcion)

    class Meta:
        verbose_name = 'Ticket'
        verbose_name_plural = 'Tickets'


class TicketAdmin(admin.ModelAdmin):
    list_display = ('titulo', 'descripcion', 'estado', 'tiempo_creacion')
    list_filter = ('titulo', 'descripcion', 'estado')
    ordering = ('fecha_creacion',)
    search_fields = ('titulo',)

ticket/forms.py
from django import forms

from ticket.models import Ticket


class TicketForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TicketForm, self).__init__(*args, **kwargs)
        if self.instance.pk is not None:
            self.fields['titulo'].widget.attrs['disabled']      = 'disabled'
            self.fields['descripcion'].widget.attrs['disabled'] = 'disabled'
            self.fields['estado'].widget.attrs['disabled']      = 'disabled'

    tipo_estado = (
        (1, 'Abierto'),
        (2, 'Pendiente'),
        (3, 'En Proceso'),
        (4, 'Resuelto'),
        (3, 'Cerrado')
    )
    estado = forms.ChoiceField(
        widget=forms.Select(attrs={
                'class': 'form-control',
                'data-actions-box':'true',
            }),
        label="Estado",
        error_messages={'required': "Requerido"},
        choices = tipo_estado
    )

    class Meta:
        model= Ticket
        fields= '__all__'

        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control',  'parsley-required':'true', 'data-parsley-required-message':'Campo requerido' }),
            'descripcion': forms.Textarea(attrs={'class': 'form-control' , 'parsley-required':'true', 'data-parsley-required-message':'Campo requerido' })
        }
        labels = {
            'titulo': 'Titulo',
            'descripcion': 'Descripcion'
        }

        error_messages = {
            'titulo': {'required': "Requerido"},
            'descripcion': {'required': "Requerido"},
        }

ticket/views.py
from django.views.generic import *
from ticket.models import Ticket
from django.http import JsonResponse
from ticket.forms import TicketForm

# Create your views here.

class TicketList(ListView):
    """
    ListView se refiere a una vista (lógica) para mostrar múltiples instancias de una tabla en la base de datos    
    Las vistas basadas en clases proporcionan una forma alternativa de implementar vistas como objetos de Python en lugar de funciones
    """
    model           = Ticket
    template_name   = 'ticket/list.html'

    def get_context_data(self, **kwargs):
        """
        Este método se utiliza para rellenar un diccionario y utilizarlo como contexto de plantilla
        Como su nombre indica obtiene los datos del contexto. Son los datos, variables, objectos, etc, que le vas a pasar al template para maquetarlos. 
        Por ejemplo es donde pasarías un formulario en caso de que necesites un template con 2 o más formularios.
        """
        context = super(TicketList, self).get_context_data(**kwargs)
        context['form'] = TicketForm
        return context

    def get_queryset(self):
        """
        Esta función es la que se encarga de obtener los objetos del modelo que le indicas en la variable model de tu clase. 
        Ésta función por defecto obtiene el queryset de la llamada model.objects.all(). 
        Puedes reescribir esta función de la misma manera que get_context_data() 
        para indicar alguna restrincción especial que necesites en esa view.
        """
        queryset = Ticket.objects.all()
        return queryset

class GetTicketList(View):

    http_method_names = ['get']

    def get(self, request):

        status  = True
        message = None
        data    = []

        try:
            tickets  = Ticket.objects.all()

            for ticket in tickets:
                valor = {}
                valor['id']               = ticket.id
                valor['titulo']           = ticket.titulo
                valor['estado']           = ticket.estado
                valor['descripcion']      = ticket.descripcion
                valor['tiempo_creacion']  = ticket.tiempo_creacion
                data.append(valor)
        
        except Exception as error:
            status = False
            message = str(error)

        return JsonResponse({
            'status': status,
            'message': message,
            'data': list(data)
        }, safe=False)

class TicketNew(FormView):

    """
    FormView se refiere a una vista (lógica) para mostrar y verificar un formulario Django. 
    Por ejemplo, un formulario para registrar usuarios. 
    Las vistas basadas en clases proporcionan una forma alternativa de implementar vistas como objetos de Python 
    en lugar de funciones
    """

    http_method_names = ['post']
    template_name     = 'ticket/list.html'
    form_class        = TicketForm
    success_url       = None

    def form_valid(self, form):
        try:
            status  = True
            message = 'Ticket Creado Correctamente'
            error   = None
            form.save()

        except Exception as error:
            status = False
            message = str(error)


        return JsonResponse({
            'status'  : status,
            'message' : message,
            'error'   : error
        })
        

ticket/templates/ticket/list.html
{% extends 'base.html' %}
{% block content %}


  
  <!-- begin #content -->
  <div id="content" class="content" style="min-height: 100vh; background: url(static/assets/img/cover/cover-scrum-board.png) no-repeat fixed; background-size: 360px; background-position: right bottom;">
    <div class="d-flex align-items-center mb-md-3 mb-2">
      <!-- begin page-header -->
      <h1 class="page-header mb-0">
        LISTA DE TICKET
      </h1>
      <!-- end page-header -->
      {% if  perms.tickets.add_ticket%}
      <div class="ml-auto">
        <a href="#modalAddTask" data-toggle="modal" class="btn btn-success btn-sm btn-rounded pl-2 pr-3"><i class="fa fa-plus mr-1"></i> Nuevo Ticket</a>
      </div>
      {% endif %}
    </div>
    <div class="row">
      <div class="col-md-12">
          <div class="panel panel-inverse">
            <div class="panel-heading">
              <h4 class="panel-title">Ticket</h4>
              <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
              </div>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                      <table id="t-tickets" class="table table-striped table-bordered" style="width: 100%!important"></table>
                    </div>
                </div>
            </div>
          </div>
      </div>
    </div>
    
    <div class="modal fade" id="modalAddTask">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
          </div>
          <form id="f-ticket" role="form" action="{% url 'ticket:ticket_new' %}"  method="post" data-parsley-validate="true">
            {% csrf_token %}
            <div class="modal-body">
              <div class="img-modal">
                <img src="/static/assets/img/modal/mticket.png" class="media-object rounded-corner">
              </div>
              <div class="form-group">
                <label>Title</label>
                {{form.titulo}} 
              </div>

              <div class="form-group">
                <label>Estado</label>
                {{form.estado}} 
              </div>

              <div class="form-group">
                <label>Descrición</label>
                {{form.descripcion}} 
              </div>
            </div>
            <div class="modal-footer">
              <a href="#" class="btn btn-white" data-dismiss="modal">Cancel</a>
              <button class="btn btn-primary" type="submit">Guardar</button>
            </div>
        </form>
      
        </div>
      </div>
    </div>
  </div>
  <!-- end #content -->
  
  
  <!-- begin scroll to top btn -->
  <a href="javascript:;" class="btn btn-icon btn-circle btn-success btn-scroll-to-top fade" data-click="scroll-top"><i class="fa fa-angle-up"></i></a>
  <!-- end scroll to top btn -->



  	
<style>
.img-modal img {
    margin: 0 auto;
    display: block;
    max-width: 125px;
    margin-top: -75px;
}

.modal-header {
    min-height: 90px;
    justify-content: flex-end;
    background: rgba(29, 97, 178, 0.2);
}
</style>
{% endblock content %}

{% block script %}
<script>

$(document).ready(function() {
  tickets = LoadTable.init({
		'id'         : '#t-tickets',
		'order'      : [1, 'asc'],
		'responsive' : true,
	  'ajax': {
		        url: "{% url 'ticket:get_ticket'%}",
		},
	  'deferRender': true,
		'buttons': [],
		'columns': [
		{
				'data': 'id',
				'title': 'ID',
				'visible': false,
		},
		{
				'data': 'titulo',
				'title': 'Título',
				'width': '30%',
		},
		{
				'data': 'descripcion',
				'title': 'Descripción',
				'width': '15%',
        'visible': false,
		},
    {
				'data': 'estado',
				'title': 'Estado',
				'width': '15%',
		},
    {
				'data': 'tiempo_creacion',
				'title': 'Días Creación',
				'width': '15%',
		},
		],

    
		'columnDefs': [
        {
          'targets': [1],
          render: function (data, type, full, meta) {
              var btns = '';
              btns += '<div class="flex-fill">'
              btns += '<div class="f-s-13 f-w-600 text-inverse">'+full.titulo+'</div>'
              btns += '<div class="mb-1 f-s-12">'
              btns += '<div class="text-inverse-lighter flex-1">#'+full.id+' generado por '+'{{request.user.username}}'+'</div>'
              btns += '<div class="text-inverse-lighter flex-1"></div>'+full.descripcion+'</div>'
              btns += '<div class="mb-1">'
              btns += '<span class="label label-primary">docs</span> ' 
              btns += '<span class="label label-success">feature</span>'
              btns += '</div>'
              btns += '<hr class="m-b-10"/>'
              btns += '</div>'
              return btns

          }
        },
		    {
          'targets': [3],
          render: function (data, type, full, meta) {
              var estados = ['Abierto', 'Pendiente', 'En Proceso', 'Resuelto', 'Cerrado']
              var btns = '';
              btns +='<div class="mr-3 f-s-16">'
              if (data == 1 || data == 2){
                btns +='<i class="fa fa-bug text-danger fa-fw"></i><span class="f-s-12">'+ estados[data-1]+'</span></div>'
              }
              else if (data == 3){
                btns +='<i class="fa fa-tools text-muted fa-fw"></i><span class="f-s-12">'+ estados[data-1]+'</span></div>'
              }
              else{
                btns +='<i class="far fa-check-circle text-success fa-fw"></i><span class="f-s-12">'+ estados[data-1]+'</span></div>'
              }
              
              return btns

          }
        },
        {
          'targets': [4],
          render: function (data, type, full, meta) {
              var btns = '';
              btns +='<div class="mr-3 f-s-16">'
              var btns = '';
              if (full.estado == 1 || full.estado == 2){
                btns += '<div class="d-flex align-items-center m-b-5">'
                btns +='<div class="f-s-12 d-flex align-items-center text-inverse f-w-600">Días ('+ data+')</div>'
                btns += '<div class="progress progress-xs width-100 mb-0 ml-2 mr-2">'
                btns += '<div class="progress-bar progress-bar-striped bg-danger" style="width: 5%;"></div>'
                btns += '</div>'
                btns += '<div class="f-s-10">0%</div>'
                btns += '</div>'
              }
              else if (full.estado  == 3){
                btns += '<div class="d-flex align-items-center m-b-5">'
                btns +='<div class="f-s-12 d-flex align-items-center text-inverse f-w-600">Días ('+ data+')</div>'
                btns += '<div class="progress progress-xs width-100 mb-0 ml-2 mr-2">'
                btns += '<div class="progress-bar progress-bar-striped bg-warning" style="width: 100%;"></div>'
                btns += '</div>'
                btns += '<div class="f-s-10">50%</div>'
                btns += '</div>'
              }
              else{
                btns += '<div class="d-flex align-items-center m-b-5">'
                btns +='<div class="f-s-12 d-flex align-items-center text-inverse f-w-600">Días ('+ data+')</div>'
                btns += '<div class="progress progress-xs width-100 mb-0 ml-2 mr-2">'
                btns += '<div class="progress-bar progress-bar-striped bg-success" style="width: 100%;"></div>'
                btns += '</div>'
                btns += '<div class="f-s-10">100%</div>'
                btns += '</div>'
              }
              
              return btns

          }
        },
		 
        ]
	})

  $('#f-ticket').submit(function(e) { 
        console.log(e)
        e.preventDefault();
        if ( $(this).parsley().isValid() ) {
          $("#f-ticket").ajaxSubmit({
            dataType: 'json',
            success: function(response) {
                location.reload();
            },
            error: function(data, a, t) {
              alert('ERROR')
            }
          });     
        }
    });

});

var LoadTable = function() {
    "use strict";
    return {
        //main function
        init: function(config) {
            var table;
            var language = {
                "decimal": "-",
                "thousands": ".",
                'emptyTable': 'Sin Datos',
                'info': 'mostranto _END_ de _TOTAL_ registros',
                'infoEmpty': '0-0 de 0',
                'infoFiltered': '',
                'infoPostFix': '',
                'lengthMenu': '_MENU_',
                'loadingRecords': 'Cargando...',
                'processing': 'Procesando...',
                'search': '',
                'searchPlaceholder': 'Buscar',
                'zeroRecords': 'No se encontraron registros',
                'paginate': {
                    'first': 'Primero',
                    'last': 'Último',
                    'next': 'Próximo',
                    'previous': 'Anterior'
                }
            };

      var buttons = [
        {
          extend: 'excel'
        },
        {
          extend: 'pdf'
        },
      ];

      if ($.fn.DataTable.isDataTable(config.id)) {
        table = $(config.id).DataTable();
        table.destroy();
        $(config.id).empty()
      }
      if (config.structure != undefined && $(config.id).length > 0) {
        $(config.id).append(config.structure.tfoot)
      }

      if ($(config.id).length !== 0) {
        table = $(config.id).DataTable({
          language: language, // lenguaje
          data: config.data == null ? false : config.data, // filas
          ajax: config.ajax == null ? false : config.ajax,
          deferRender: config.deferRender == null ? false : config.deferRender,
          order: config.order == null ? [
            [0, 'asc']
          ] : config.order, // columna a ordenar
          info: config.info == null ? true : config.info, // info
          responsive: config.responsive == null ? true : config.responsive,
          stateSave: config.stateSave == null ? true: config.stateSave,
          columns: config.columns == null ? [] : config.columns, // columnas
          columnDefs: config.columnDefs == null ? [] : config.columnDefs,
          paginate: config.paginate == null ? true : config.paginate, // paginador
          pageLength: config.pageLength == null ? 10 : config.pageLength, // elementos a mostar por defecto
          bLengthChange: config.bLengthChange == null ? true : config.bLengthChange, // elementos a mostrar
          searching: config.searching == null ? true : config.searching, // buscar
          ordering: config.ordering == null ? true : config.ordering, // ordenar
          drawCallback: config.drawCallback == null ? function(){} : config.drawCallback,
          pagingType: config.pagingType == null ? 'simple_numbers' : config.pagingType,
          dom: '<"top"lf<"btn-search">B><"form-search">rt<"bottom"ip>',
          buttons: config.buttons == null ? buttons : config.buttons,
          footerCallback: config.footerCallback == null ? function() {} : config.footerCallback,
        });
      }
      return table
    }
  };
}();


</script>
{% endblock %}