DjangoTest/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path


urlpatterns = [
     
    path('', include('authenticate.urls')),
    path('', include('ticket.urls')),
    path('admin/', admin.site.urls),
]

authenticate/urls.py
from django.urls import path

from .views import *
from django.contrib.auth import views as auth_views

app_name = 'authenticate'

urlpatterns = [

    # login
    path('login/', Login.as_view(), name='login'),
    # logout
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name="logout"),
]

ticket/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from ticket.views import *

app_name = 'ticket'

urlpatterns = [
    path('', login_required(TicketList.as_view()), name='list'),
    path('get-tickets/', GetTicketList.as_view(), name='get_ticket'),
    path('new/', login_required(TicketNew.as_view()), name='ticket_new'),
]

templates/partial/footer.html
{% load static %}
<div id="footer" class="footer">
    &copy; 2021 Uwigo - All Rights Reserved
</div>

templates/partial/top-bar.html
{% load static %}
<div id="header" class="header navbar-default">
    <!-- begin navbar-header -->
    <div class="navbar-header">
        <a href="/" class="navbar-brand"><span class="navbar-logo"></span> <b>UWIGO</b>  soporte</a>
    </div>
    <!-- end navbar-header -->
    <!-- begin header-nav -->
    <ul class="navbar-nav navbar-right">
     
        <li class="dropdown navbar-user">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <img src="static/assets/img/user/user-13.jpg" alt="" /> 
                <span class="d-none d-md-inline">{{user.username}}</span> <b class="caret"></b>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="javascript:;" class="dropdown-item">Editar Perfil</a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'authenticate:logout' %}" class="dropdown-item">Salir</a>
            </div>
        </li>
    </ul>
    <!-- end header-nav -->
</div>